version: "3"
services:
  app:
    restart: unless-stopped
    image: node:20.11.1
    volumes:
      - .:/project
    working_dir: /project
    command: "node dist/index.js"
    ports:
      - 3005:3005
    environment:
      - NODE_ENV=production
