version: "3"
services:
  app:
    restart: unless-stopped
    build: .
    volumes:
      - .:/project
    working_dir: /project
    ports:
      - 3005:3005
    environment:
      - NODE_ENV=production
