import { Reason } from "./Reason";

describe("parts()", () => {
	const tests = [
		["WX:Fog", ["WX", "Fog"]],
		["fog", ["WX", "Fog"]],
		["WX:Low Ceilings", ["WX", "Low Ceilings"]],
		["low ceilings", ["WX", "Low Ceilings"]],
		["WX:Thunderstorms", ["WX", "Thunderstorms"]],
		["WX: THUNDERSTORMS", ["WX", "THUNDERSTORMS"]],
		["thunderstorms", ["WX", "Thunderstorms"]],
		["WX:Wind", ["WX", "Wind"]],
		["wind", ["WX", "Wind"]],
		["WIND", ["WX", "Wind"]],
		["WX:Snow/Ice", ["WX", "Snow/Ice"]],
		["snow or ice", ["WX", "Snow/Ice"]],
		["SNOW/ICE", ["WX", "Snow/Ice"]],
		["snow or Ice mitigation or treatment", ["WX", "Snow/Ice"]],
		["WX:WINDSHEAR/MICROBURST", ["WX", "WINDSHEAR/MICROBURST"]],
		["WX:Tornado/Hurricane", ["WX", "Tornado/Hurricane"]],
		["low visibility", ["WX", "Low Visibility"]],
		["WX VIS", ["WX", "Low Visibility"]],
		["WX:Low Visibility", ["WX", "Low Visibility"]],
		["RAIN", ["WX", "Rain"]],
		["rain", ["WX", "Rain"]],
		["WX:Rain", ["WX", "Rain"]],
		["TORNADO/HURRICANE", ["WX", "Tornado/Hurricane"]],
		["tornado or hurricane", ["WX", "Tornado/Hurricane"]],
		["WX:Tornado/Hurricane", ["WX", "Tornado/Hurricane"]],
		["WX:SEV TURB", ["WX", "SEV TURB"]],
		["ZDV/WX:WIND SHEAR", ["WX", "WIND SHEAR"]],
		["ZDV/WX:MICROBURSTS", ["WX", "MICROBURSTS"]],
		["RWY:Noise Abatement", ["RWY", "Noise Abatement"]],
		["RWY:Maintenance", ["RWY", "Maintenance"]],
		["RWY:MAINTENANCE", ["RWY", "MAINTENANCE"]],
		["runway maintenance", ["RWY", "Maintenance"]],
		["RWY:Construction", ["RWY", "Construction"]],
		["runway construction", ["RWY", "Construction"]],
		["RWY:Rwy Change - Operational Necessity", ["RWY", "Rwy Change - Operational Necessity"]],
		["RWY:Rwy Change - Operational Advantage", ["RWY", "Rwy Change - Operational Advantage"]],
		["runway configuration change", ["RWY", "Rwy Change - Operational Necessity"]],
		["RWY:Disabled Aircraft", ["RWY", "Disabled Aircraft"]],
		["RWY: DISABLED AIRCRAFT", ["RWY", "DISABLED AIRCRAFT"]],
		["OTHER: DISABLED AIRCRAFT", ["OTHER", "DISABLED AIRCRAFT"]],
		["disabled aircraft on the runway", ["RWY", "Disabled Aircraft"]],
		["RWY:Obstruction", ["RWY", "Obstruction"]],
		["runway obstruction", ["RWY", "Obstruction"]],
		["TWY:CONSTRUCTION", ["TWY", "CONSTRUCTION"]],
		["TM Initiatives:MIT:VOL", ["TM Initiatives", "MIT", "VOL"]],
		["TM Initiatives:MINIT:VOL", ["TM Initiatives", "MINIT", "VOL"]],
		["TM Initiatives:DSP:VOL", ["TM Initiatives", "DSP", "VOL"]],
		["TM Initiatives:MIT:WX", ["TM Initiatives", "MIT", "WX"]],
		["TM Initiatives:STOP:WX", ["TM Initiatives", "STOP", "WX"]],
		["TM Initiatives:Other:STAFFING", ["TM Initiatives", "Other", "STAFFING"]],
		["TM Initiatives:STOP:VOL", ["TM Initiatives", "STOP", "VOL"]],
		["TM Initiatives:STOP:STAFFING", ["TM Initiatives", "STOP", "STAFFING"]],
		["TM Initiatives:Other:VOL", ["TM Initiatives", "Other", "VOL"]],
		["TM Initiatives:MIT:STAFFING", ["TM Initiatives", "MIT", "STAFFING"]],
		["TM Initiatives:MINIT: STAFFING", ["TM Initiatives", "MINIT", "STAFFING"]],
		["TM Initiatives:MINIT:STAFFING", ["TM Initiatives", "MINIT", "STAFFING"]],
		["TM Initiatives:MINIT:STAFF", ["TM Initiatives", "MINIT", "STAFF"]],
		["TM Initiatives:MIT:STAFF", ["TM Initiatives", "MIT", "STAFF"]],
		["TM INITIATIVES:STOP:STAFFING", ["TM INITIATIVES", "STOP", "STAFFING"]],
		["VOL:Compacted Demand", ["VOL", "Compacted Demand"]],
		["VOL:Multi-taxi", ["VOL", "Multi-taxi"]],
		["VOL:Volume", ["VOL", "Volume"]],
		["VOLUME", ["VOL", "Volume"]],
		["airport volume", ["VOL", "Volume"]],
		["ZDC/VOL:Volume", ["VOL", "Volume"]],
		["STAFF:ZNY STAFFING", ["STAFF", "ZNY STAFFING"]],
		["STAFFING", ["STAFF", "Staffing"]],
		["EQ:RWY08R LGTG OTS", ["EQ", "RWY08R LGTG OTS"]],
		["equipment outage", ["EQ"]],
		["EQUIPMENT", ["EQ"]],
		["EQ: RADAR OUTAGE", ["EQ", "RADAR OUTAGE"]],
		["EQ:RADAR", ["EQ", "RADAR"]],
		["air show", ["OTHER", "Air Show"]],
		["OTHER:Military OPS", ["OTHER", "Military OPS"]],
		["MILITARY", ["OTHER", "Military OPS"]],
		["military operations", ["OTHER", "Military OPS"]],
		["OTHER:Bird Strike", ["OTHER", "Bird Strike"]],
		["bird strike", ["OTHER", "Bird Strike"]],
		["OTHER:Aircraft Emergency", ["OTHER", "Aircraft Emergency"]],
		["aircraft emergency", ["OTHER", "Aircraft Emergency"]],
		["OTHER:FACILITY ENVIRONMENTAL ISSUE", ["OTHER", "FACILITY ENVIRONMENTAL ISSUE"]],
		["OTHER:DOG ON RUNWAYS", ["OTHER", "DOG ON RUNWAYS"]],
		["OTHER: S&R OPS", ["OTHER", "S&R OPS"]],
		["airspace volume", ["VOL", "Volume"]],
		["disabled aircraft on the runway", ["RWY", "Disabled Aircraft"]],
		["runway maintenance", ["RWY", "Maintenance"]],
		["VIPM:VIP Movement", ["VIPM", "VIP Movement"]],
	];

	test.each(tests)("parts(%p) === %p", (input, expected) => {
		const reason = new Reason(input as string);
		expect(reason.parts()).toStrictEqual(expected);
	});
});

describe("parentType()", () => {
	const tests = [
		["WX:Fog", "WX"],
		["fog", "WX"],
		["WX:Low Ceilings", "WX"],
		["low ceilings", "WX"],
		["WX:Thunderstorms", "WX"],
		["WX: THUNDERSTORMS", "WX"],
		["thunderstorms", "WX"],
		["WX:Wind", "WX"],
		["wind", "WX"],
		["WIND", "WX"],
		["WX:Snow/Ice", "WX"],
		["snow or ice", "WX"],
		["SNOW/ICE", "WX"],
		["snow or Ice mitigation or treatment", "WX"],
		["WX:WINDSHEAR/MICROBURST", "WX"],
		["WX:Tornado/Hurricane", "WX"],
		["low visibility", "WX"],
		["WX VIS", "WX"],
		["WX:Low Visibility", "WX"],
		["RAIN", "WX"],
		["rain", "WX"],
		["WX:Rain", "WX"],
		["TORNADO/HURRICANE", "WX"],
		["tornado or hurricane", "WX"],
		["WX:Tornado/Hurricane", "WX"],
		["WX:SEV TURB", "WX"],
		["ZDV/WX:WIND SHEAR", "WX"],
		["ZDV/WX:MICROBURSTS", "WX"],
		["RWY:Noise Abatement", "RWY"],
		["RWY:Maintenance", "RWY"],
		["RWY:MAINTENANCE", "RWY"],
		["runway maintenance", "RWY"],
		["RWY:Construction", "RWY"],
		["runway construction", "RWY"],
		["RWY:Rwy Change - Operational Necessity", "RWY"],
		["RWY:Rwy Change - Operational Advantage", "RWY"],
		["runway configuration change", "RWY"],
		["RWY:Disabled Aircraft", "RWY"],
		["RWY: DISABLED AIRCRAFT", "RWY"],
		["OTHER: DISABLED AIRCRAFT", "OTHER"],
		["disabled aircraft on the runway", "RWY"],
		["RWY:Obstruction", "RWY"],
		["runway obstruction", "RWY"],
		["TWY:CONSTRUCTION", "TWY"],
		["TM Initiatives:MIT:VOL", "TM Initiatives"],
		["TM Initiatives:MINIT:VOL", "TM Initiatives"],
		["TM Initiatives:DSP:VOL", "TM Initiatives"],
		["TM Initiatives:MIT:WX", "TM Initiatives"],
		["TM Initiatives:STOP:WX", "TM Initiatives"],
		["TM Initiatives:Other:STAFFING", "TM Initiatives"],
		["TM Initiatives:STOP:VOL", "TM Initiatives"],
		["TM Initiatives:STOP:STAFFING", "TM Initiatives"],
		["TM Initiatives:Other:VOL", "TM Initiatives"],
		["TM Initiatives:MIT:STAFFING", "TM Initiatives"],
		["TM Initiatives:MINIT: STAFFING", "TM Initiatives"],
		["TM Initiatives:MINIT:STAFFING", "TM Initiatives"],
		["TM Initiatives:MINIT:STAFF", "TM Initiatives"],
		["TM Initiatives:MIT:STAFF", "TM Initiatives"],
		["TM INITIATIVES:STOP:STAFFING", "TM Initiatives"],
		["VOL:Compacted Demand", "VOL"],
		["VOL:Multi-taxi", "VOL"],
		["VOL:Volume", "VOL"],
		["VOLUME", "VOL"],
		["airport volume", "VOL"],
		["ZDC/VOL:Volume", "VOL"],
		["STAFF:ZNY STAFFING", "STAFF"],
		["STAFFING", "STAFF"],
		["EQ:RWY08R LGTG OTS", "EQ"],
		["equipment outage", "EQ"],
		["EQUIPMENT", "EQ"],
		["EQ: RADAR OUTAGE", "EQ"],
		["EQ:RADAR", "EQ"],
		["air show", "OTHER"],
		["OTHER:Military OPS", "OTHER"],
		["MILITARY", "OTHER"],
		["military operations", "OTHER"],
		["OTHER:Bird Strike", "OTHER"],
		["bird strike", "OTHER"],
		["OTHER:Aircraft Emergency", "OTHER"],
		["aircraft emergency", "OTHER"],
		["OTHER:FACILITY ENVIRONMENTAL ISSUE", "OTHER"],
		["OTHER:DOG ON RUNWAYS", "OTHER"],
		["OTHER: S&R OPS", "OTHER"],
		["airspace volume", "VOL"],
		["disabled aircraft on the runway", "RWY"],
		["runway maintenance", "RWY"],
		["VIPM:VIP Movement", "VIPM"],
	];

	test.each(tests)("parts(%p) === %p", (input, expected) => {
		const reason = new Reason(input as string);
		expect(reason.parentType()).toStrictEqual(expected);
	});
});

describe("toString()", () => {
	const tests = [
		["WX:Fog", "fog"],
		["fog", "fog"],
		["WX:Low Ceilings", "low ceilings"],
		["low ceilings", "low ceilings"],
		["WX:Thunderstorms", "thunderstorms"],
		["WX: THUNDERSTORMS", "thunderstorms"],
		["thunderstorms", "thunderstorms"],
		["WX:Wind", "wind"],
		["wind", "wind"],
		["WIND", "wind"],
		["WX:Snow/Ice", "snow/ice"],
		["snow or ice", "snow/ice"],
		["SNOW/ICE", "snow/ice"],
		["snow or Ice mitigation or treatment", "snow/ice"],
		["WX:WINDSHEAR/MICROBURST", "wind shear/microburst"],
		["WX:Tornado/Hurricane", "a tornado/hurricane"],
		["low visibility", "low visibility"],
		["WX VIS", "low visibility"],
		["WX:Low Visibility", "low visibility"],
		["RAIN", "rain"],
		["rain", "rain"],
		["WX:Rain", "rain"],
		["TORNADO/HURRICANE", "a tornado/hurricane"],
		["tornado or hurricane", "a tornado/hurricane"],
		["WX:Tornado/Hurricane", "a tornado/hurricane"],
		["WX:SEV TURB", "severe turbulence"],
		["ZDV/WX:WIND SHEAR", "wind shear"],
		["ZDV/WX:MICROBURSTS", "microbursts"],
		["RWY:Noise Abatement", "noise reduction measures"],
		["RWY:Maintenance", "runway maintenance"],
		["RWY:MAINTENANCE", "runway maintenance"],
		["runway maintenance", "runway maintenance"],
		["RWY:Construction", "runway construction"],
		["runway construction", "runway construction"],
		["RWY:Rwy Change - Operational Necessity", "a runway change"],
		["RWY:Rwy Change - Operational Advantage", "a runway change"],
		["runway configuration change", "a runway change"],
		["RWY:Disabled Aircraft", "a disabled aircraft"],
		["RWY: DISABLED AIRCRAFT", "a disabled aircraft"],
		["OTHER: DISABLED AIRCRAFT", "a disabled aircraft"],
		["disabled aircraft on the runway", "a disabled aircraft"],
		["RWY:Obstruction", "runway obstruction"],
		["runway obstruction", "runway obstruction"],
		["TWY:CONSTRUCTION", "taxiway construction"],
		["TM Initiatives:MIT:VOL", "heavy traffic volume"],
		["TM Initiatives:MINIT:VOL", "heavy traffic volume"],
		["TM Initiatives:DSP:VOL", "heavy traffic volume"],
		["TM Initiatives:MIT:WX", "weather"],
		["TM Initiatives:STOP:WX", "weather"],
		["TM Initiatives:Other:STAFFING", "staffing constraints"],
		["TM Initiatives:STOP:VOL", "heavy traffic volume"],
		["TM Initiatives:STOP:STAFFING", "staffing constraints"],
		["TM Initiatives:Other:VOL", "heavy traffic volume"],
		["TM Initiatives:MIT:STAFFING", "staffing constraints"],
		["TM Initiatives:MINIT: STAFFING", "staffing constraints"],
		["TM Initiatives:MINIT:STAFFING", "staffing constraints"],
		["TM Initiatives:MINIT:STAFF", "staffing constraints"],
		["TM Initiatives:MIT:STAFF", "staffing constraints"],
		["TM INITIATIVES:STOP:STAFFING", "staffing constraints"],
		["VOL:Compacted Demand", "traffic management initiatives"],
		["VOL:Multi-taxi", "traffic management initiatives"],
		["VOL:Volume", "high traffic volume"],
		["VOLUME", "high traffic volume"],
		["airport volume", "high traffic volume"],
		["ZDC/VOL:Volume", "high traffic volume"],
		["STAFF:ZNY STAFFING", "staffing constraints"],
		["STAFFING", "staffing constraints"],
		// I THINK this means "Equipment: Runway 08R Lighting Out of Service"
		// The FAA Glossary (https://www.fly.faa.gov/Products/Glossary_of_Terms/glossary_of_terms.html) confirms that "OTS" means "Out of Service"
		// It says "EQUIP" is "Equipment", not "EQ"... (so not sure if `EQ` means something different)
		// But for now, we'll go with this until we figure out something different.
		["EQ:RWY08R LGTG OTS", "an equipment outage"],
		["equipment outage", "an equipment outage"],
		["EQUIPMENT", "an equipment outage"],
		["EQ: RADAR OUTAGE", "a radar equipment outage"],
		["EQ:RADAR", "a radar equipment outage"],
		["air show", "an air show"],
		["OTHER:Military OPS", "military operations"],
		["MILITARY", "military operations"],
		["military operations", "military operations"],
		["OTHER:Bird Strike", "a bird strike"],
		["bird strike", "a bird strike"],
		["OTHER:Aircraft Emergency", "an aircraft emergency"],
		["aircraft emergency", "an aircraft emergency"],
		["OTHER:FACILITY ENVIRONMENTAL ISSUE", "a facility environmental issue"],
		["OTHER:DOG ON RUNWAYS", "a dog on the runway"],
		["OTHER: S&R OPS", "search and rescue operations"],
		["airspace volume", "high traffic volume"],
		["disabled aircraft on the runway", "a disabled aircraft"],
		["runway maintenance", "runway maintenance"],
		["VIPM:VIP Movement", "VIP movement"],
	];

	test.each(tests)("parts(%p) === %p", (input, expected) => {
		const reason = new Reason(input as string);
		expect(reason.toString()).toStrictEqual(expected);
	});
});
